# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds.

  # scrape_timeout is set to the global default (10s).
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.196.202:9090']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.196.202:9100', '192.168.196.2:9100']
  - job_name: 'nvidia-dcgm-exporter'
    static_configs:
      - targets: ['192.168.196.202:9400', '192.168.196.2:9400']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - 192.168.196.202:8080
          - 192.168.196.2:8080
